import { Geist, Geist_Mono, Gwendolyn } from 'next/font/google';
import './globals.css';

import { Navbar } from '@/component/navbar/Navbar';
import Footer from '@/component/Footer/Footer';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});


const gwendolyn = Gwendolyn({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-gwendolyn',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gwendolyn.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
